#!/bin/bash

echo "🚀 Push to GitHub Guide"
echo "========================"
echo ""
echo "Step 1: Create a repository on GitHub.com"
echo "   - Go to: https://github.com/new"
echo "   - Name it: voice-clone-pdf-reader"
echo "   - Don't initialize with README (we already have one)"
echo ""
echo "Step 2: Run these commands:"
echo ""
echo "# Add your GitHub repository as remote:"
echo "git remote add origin https://github.com/YOUR_USERNAME/voice-clone-pdf-reader.git"
echo ""
echo "# Switch branch to 'main' (if needed):"
echo "git branch -M main"
echo ""
echo "# Push to GitHub:"
echo "git push -u origin main"
echo ""
echo "Step 3: Enter your GitHub credentials when prompted"
echo ""

